### ISSUE TITLE
Please review the problem statement 

### ISSUE THREAD

**Issue by liziscool** [liziscool/cas741_project#1]
Hi,
Please review my problem statement. Thanks!

**Comment by smiths** [comment]
Sounds good @liziscool.  Here are some comments that can help you improve the document:

- Please consult the writing checklist (in the docs folder of the blank project template).  The checklist will help with improving your writing, by, for instance, removing Low Information Content phrases like "in order to".  (Replace "in order to" by "to").
- Include the files from the blank project template, like the Comments.tex file
- For the issue tracker, please include the commit hash that contains the document to be reviewed
- After a period that doesn't end a sentence in LaTeX include a `.\` (see the writing checklist).  In  your document this is relevant for the `i.e.`.
- Good use of the author comments (although I cannot compile locally because the Comments.tex file is missing).  In answer to your question, as long as there are no privacy concerns, I think the problem statement is improved if you add the name of the company.  There is no harm in being specific about the stakeholders
- Listing the supported OS seems too concrete to me.  Is this a real constraint?  If it is, you should justify it, say be saying that it is an imposed requirement of the company.
- In the tex document hard-wrap the lines at 80 characters
- You should include the `.gitignore` file from the blank project template
- You should remove from version control the `.DS_Store` file that shows up in at least one of your folders
- You should add your real name to your profile

Once you address the above points, I can close this issue, and approve your problem statement.

**Comment by liziscool** [comment]
I hope I have fixed everything correctly with fe2fe64f00176c97a4f38edf5e9b484275af51d2 <- Hopefully, this is the correct way to include the commit hash.

Or perhaps the link is better [https://github.com/liziscool/cas741_project/tree/master/docs/ProblemStatement](url)

**Comment by smiths** [comment]
The changes look good @liziscool.  With respect to giving the commit hash or a link, the commit hash is preferable, since it includes the diff.  The refinement I would suggest in the future is to do smaller commits.  Each commit should do one thing.  That way you can give complete traceability between each request and the changes that satisfy that request.  Smaller commits are also really useful when there are multiple developers and the strong possibility of a merge conflict.

In LaTeX, your `i.\ e.\ ` should be `i.e.\`; that is, you don't want the space between the `i` and the `e`.  The final slash means that there will be only one space after the e, instead of the two spaces that LaTeX introduces for the end of a sentence.

I'll approve your problem statement.
