### ISSUE TITLE
Properties of a correct solution 

### ISSUE THREAD

**Issue by muralidn** [liziscool/cas741_project#17]
@liziscool 

I don't think the first sentence of 4.2.6 is necessary, as the rest of the paragraph appears to concisely describe the properties of a correct solution. Plus I don't think it is necessary to state the obvious (sentence highlighted in orange). 

![image](https://user-images.githubusercontent.com/71282513/95913433-d5198200-0dc1-11eb-943e-f6d431c0237a.png)

**Comment by liziscool** [comment]
Hmm, perhaps I was unable to describe the problem I am going to have with identifying a correct solution.  For an input signal x(n) the output should be a time-frequency representation of the signal, but what does a time-frequency representation look like (it can vary) and how do you know if its a 'correct' time-frequency representation?  It's subjective since there is no perfect time-frequency representation, that is why it is a 'representation'. I will look into re-wording it, but i do think the sentance highlighted in orange is important since I will want to test the program by comparing outputs of similar signals...

**Comment by muralidn** [comment]
Perfect, thanks for the clarification! 

I don't have any idea about this domain, so apologies in advance for any 'dumb' issues.

**Comment by liziscool** [comment]
No no, don't worry I really appreciate these issues! I've been struggling with explaining what I am trying to do so it is very helpful to me to help figure out what to clarify, and just for me personally to figure out my own process.

**Comment by smiths** [comment]
@liziscool, you are applying equations to solve your problem so a correct solution is one that applies the equations properly.  I need to look more closely at your SRS, but I feel like there is some confusion between the SRS and the VnV plan.  Your SRS should say the equations you are applying and your VnV plan describes how you are going to assess how useful the solutions are.
