### ISSUE TITLE
Add complexity somewhere

### ISSUE THREAD

**Issue by smiths** [liziscool/cas741_project#2]
@liziscool, I didn't have a chance to give you complete feedback on your presentation.  Your project looks great, but as it is right now, it is a little on the simple side.  This isn't necessarily a bad thing.  A simpler project can be done to very high quality, but to get the most out of the course, you should add some complexity somewhere.  You can add the complexity in your project scope, or you can add complexity as we go along, for instance through testing, improved usability, etc.

Once you have reviewed my feedback, you can close this issue.

**Comment by liziscool** [comment]
@smiths Of course. I was considering also doing wavelet transforms since they are applied similarly to the way an STFT is applied. I thought I would "scope down" to one kind of transform for simplicity, but I can easily scope back up so that the project is capable of computing different kinds of time-frequency analysis (i.e. STFT, wavelet, there are others too), as chosen by the user.

**Comment by smiths** [comment]
@liziscool, the decision on whether to scope "up" or "down" is entirely up to you.  My only point was that every project will ideally have some area in which it "shines."  I'm not sure if I conveyed this during our lectures.  In the scope of a 12.5 week course, it isn't feasible for every project to excel in every aspect of the course.  If you choose to make your impact with the quality of your documentation and testing, rather than by having a broader scope to your project, that is also fine.
